package com.aws.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import java.io.Serializable;
import java.util.List;

@DynamoDBTable(tableName = "environments")
public class Environments implements Serializable {
    private static final long serialVersionUID = 1L;

    private String envId;
    private List<User> users;
    private String envName;

    public Environments() {
    }

    @DynamoDBHashKey(attributeName = "envId")
    @DynamoDBAutoGeneratedKey
    public String getEnvId() {
        return envId;
    }

    public void setEnvId(String envId) {
        this.envId = envId;
    }

    @DynamoDBAttribute
    public List<User> getUsers() {
        return users;
    }

    public void setUsers(List<User> users) {
        this.users = users;
    }

    @DynamoDBAttribute
    public String getEnvName() {
        return envName;
    }

    public void setEnvName(String envName) {
        this.envName = envName;
    }

    @Override
    public String toString() {
        return "Environments{" +
                "envId='" + envId + '\'' +
                ", users=" + users +
                ", envName='" + envName + '\'' +
                '}';
    }
}
